POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1haWJiIiwiaWQiOiI1ZWNiNzY2MmNjZGUwZDc5ZWQ1MTBjNDYiLCJpYXQiOjE1OTAzOTI0NTF9.OPRcf973JpWAu432NDguORTL_5HrD4cwXVIEdmai_WE

{
    "title": "How to be a bear",
    "author": "Bear",
    "url": "www.bear.com",
    "userId": "5ecb7662ccde0d79ed510c46"
}